import gradio as gr
import torch
import torch.nn.functional as F
from PIL import Image
import os
import sys
import numpy as np
import datetime
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib.colors import HexColor

# Import project modules
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from models.classifier import get_brain_classifier, get_knee_classifier
from models.encoder import get_encoder
from utils.augmentations import get_val_transform
from utils.grad_cam import GradCAM, overlay_heatmap

# ==========================================
# CONFIGURATION & SETUP
# ==========================================

DEVICE = torch.device("cpu") 
print(f"System configured to use: {DEVICE}")

# Define Constants
BRAIN_MODEL_PATH = os.path.join("models", "brain_model.pth")
KNEE_MODEL_PATH = os.path.join("models", "knee_model.pth")

BRAIN_CLASSES = ["Glioma", "Meningioma", "No Tumor", "Pituitary"]
KNEE_CLASSES = ["Grade 0", "Grade 1", "Grade 2", "Grade 3", "Grade 4"]

# ==========================================
# PDF GENERATION
# ==========================================

def generate_report(image, heatmap, diagnosis_text, probability_text):
    """
    Generates a PDF report using ReportLab.
    """
    if image is None:
        return None

    # Create reports directory
    os.makedirs("reports", exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"reports/SSCLNet_Report_{timestamp}.pdf"
    
    # Define temp image paths
    temp_img_path = f"reports/temp_img_{timestamp}.jpg"
    temp_cam_path = f"reports/temp_cam_{timestamp}.jpg"
    
    try:
        # Save temp images for insertion
        if isinstance(image, np.ndarray):
            Image.fromarray(image).save(temp_img_path)
        else:
            image.save(temp_img_path) # Assumed PIL
            
        # Heatmap Image
        if isinstance(heatmap, np.ndarray):
            Image.fromarray(heatmap).save(temp_cam_path)
        else:
             if heatmap is not None:
                heatmap.save(temp_cam_path)
        
        # Create PDF
        c = canvas.Canvas(filename, pagesize=letter)
        width, height = letter
        
        # Header
        c.setFillColor(HexColor("#0f766e")) # Teal
        c.setFont("Helvetica-Bold", 24)
        c.drawString(50, height - 50, "SSCLNet Diagnostic Report")
        
        c.setFillColor(HexColor("#334155")) # Slate
        c.setFont("Helvetica", 12)
        c.drawString(50, height - 75, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}")
        c.drawString(50, height - 90, f"Report ID: {timestamp}")
        
        c.line(50, height - 100, width - 50, height - 100)
        
        # Diagnosis Section
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, height - 140, "Diagnostic Assessment")
        
        c.setFont("Helvetica", 14)
        c.setFillColor(HexColor("#000000"))
        c.drawString(50, height - 170, f"Predicted Condition: {diagnosis_text}")
        c.drawString(50, height - 190, f"Model Confidence: {probability_text}")

        # Images Section
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, height - 240, "Visual Analysis")
        
        # Draw images (Resize to fit)
        c.drawString(50, height - 265, "Original Scan")
        c.drawImage(temp_img_path, 50, height - 500, width=220, height=220, preserveAspectRatio=True)
        
        if os.path.exists(temp_cam_path):
            c.drawString(300, height - 265, "Attention Map (Grad-CAM)")
            c.drawImage(temp_cam_path, 300, height - 500, width=220, height=220, preserveAspectRatio=True)
        
        # Footer
        c.setFont("Helvetica-Oblique", 10)
        c.setFillColor(HexColor("#64748b"))
        c.drawString(50, 50, "Generated by SSCLNet.")
        
        c.save()
        
        # Cleanup temp files
        if os.path.exists(temp_img_path): os.remove(temp_img_path)
        if os.path.exists(temp_cam_path): os.remove(temp_cam_path)
            
        return filename

    except Exception as e:
        print(f"PDF Error: {e}")
        return None

# ==========================================
# MODEL LOADING
# ==========================================

def load_system_models():
    """
    Loads both Brain and Knee models safely with Grad-CAM hooks.
    """
    try:
        print("Initializing models...")
        
        brain_encoder = get_encoder(pretrained=False)
        brain_net = get_brain_classifier(encoder=brain_encoder, num_classes=len(BRAIN_CLASSES))
        
        if os.path.exists(BRAIN_MODEL_PATH):
            state_dict = torch.load(BRAIN_MODEL_PATH, map_location=DEVICE)
            brain_net.load_state_dict(state_dict)
        else:
            print(f"⚠️ Warning: {BRAIN_MODEL_PATH} not found.")
        
        brain_net.to(DEVICE)
        brain_net.eval()
        
        brain_cam = GradCAM(brain_net, brain_net.encoder[7])
        
        knee_encoder = get_encoder(pretrained=False)
        knee_net = get_knee_classifier(encoder=knee_encoder, num_classes=len(KNEE_CLASSES))
        
        if os.path.exists(KNEE_MODEL_PATH):
            state_dict = torch.load(KNEE_MODEL_PATH, map_location=DEVICE)
            knee_net.load_state_dict(state_dict)
        else:
            print(f"⚠️ Warning: {KNEE_MODEL_PATH} not found.")
            
        knee_net.to(DEVICE)
        knee_net.eval()
        
        knee_cam = GradCAM(knee_net, knee_net.encoder[7])
        
        return (brain_net, brain_cam), (knee_net, knee_cam)

    except Exception as e:
        print(f"❌ Critical Error loading models: {e}")
        return (None, None), (None, None)

(brain_model, brain_cam_tool), (knee_model, knee_cam_tool) = load_system_models()
transform = get_val_transform()

# ==========================================
# INFERENCE LOGIC WITH EXPLAINABILITY
# ==========================================

def predict_advanced(image, task):
    if image is None:
        return None, None, gr.HTML(""), "", ""

    try:
        pil_image = Image.fromarray(image).convert("RGB")
        img_tensor = transform(pil_image).unsqueeze(0).to(DEVICE)

        with torch.enable_grad():
            if task == "Brain MRI":
                if brain_model is None: raise gr.Error("Brain Model not loaded.")
                model = brain_model
                cam_tool = brain_cam_tool
                classes = BRAIN_CLASSES
            elif task == "Knee Osteoarthritis":
                if knee_model is None: raise gr.Error("Knee Model not loaded.")
                model = knee_model
                cam_tool = knee_cam_tool
                classes = KNEE_CLASSES
            else:
                raise gr.Error("Invalid Task")

            outputs = model(img_tensor)
            probs = F.softmax(outputs, dim=1)[0].detach().numpy()
            
            top_class_idx = np.argmax(probs)
            top_class_label = classes[top_class_idx]
            confidence_val = probs[top_class_idx]*100
            
            heatmap = cam_tool(img_tensor, class_idx=top_class_idx)
            vis_img = overlay_heatmap(heatmap, pil_image)
            
            label_dict = {classes[i]: float(probs[i]) for i in range(len(classes))}
            
            html_output = f"""
            <div style='background-color: #f0fdf4; padding: 15px; border-radius: 10px; border: 1px solid #bbf7d0;'>
                <h3 style='color: #166534; margin: 0;'>Diagnosis: {top_class_label}</h3>
                <p style='color: #15803d; font-size: 14px; margin-top: 5px;'>Confidence: <strong>{confidence_val:.1f}%</strong></p>
            </div>
            """
            
            # Return raw strings for the PDF generator state as well
            return label_dict, vis_img, html_output, top_class_label, f"{confidence_val:.1f}%"

    except Exception as e:
        raise gr.Error(f"Analysis failed: {str(e)}")

def generate_pdf_wrapper(image, heatmap, diagnosis, confidence):
    if not diagnosis or not confidence:
        raise gr.Error("Please run analysis first.")
    
    path = generate_report(image, heatmap, diagnosis, confidence)
    return path

# ==========================================
# UI CONSTRUCTION (Gradio Blocks)
# ==========================================

def create_app_v2():
    with gr.Blocks(title="SSCLNet Analysis") as app:
        
        # Hidden states to store strings for PDF report
        diagnosis_state = gr.State()
        confidence_state = gr.State()

        # Header Area
        with gr.Row():
            with gr.Column(scale=1): # Use full width column effectively for centering
                gr.HTML("""
                <h1 style="text-align: center; margin-bottom: 0;">🏥 <strong>SSCLNet Medical Image Analysis</strong></h1>
                """)
        
        gr.Markdown("---")
        
        # Main Layout: Sidebar + Content
        with gr.Row():
            
            # LEFT SIDEBAR: Controls
            with gr.Column(scale=1, variant="panel"):
                
                task_selector = gr.Radio(
                    ["Brain MRI", "Knee Osteoarthritis"],
                    label="Clinical Task",
                    value="Brain MRI",
                    info="Select valid model pipeline"
                )
                
                input_image = gr.Image(
                    type="numpy", 
                    label="Patient Scan",
                    sources=["upload"],
                    height=300
                )
                
                run_btn = gr.Button("🔍 Run Analysis", variant="primary", size="lg")
                clear_btn = gr.Button("🗑️ Reset Workspace", variant="secondary")
                
                gr.Markdown("---")
                gr.Markdown("### 📄 Reporting")
                report_btn = gr.Button("Download Medical Report")
                report_file = gr.File(label="PDF Report")

            
            # RIGHT CONTENT: Results
            with gr.Column(scale=2):
                gr.Markdown("### 📊 Diagnostic Results")
                
                # Tabbed Output
                with gr.Tabs():
                    with gr.TabItem("📈 Prediction"):
                        result_html = gr.HTML(label="Top Diagnosis")
                        conf_labels = gr.Label(num_top_classes=4, label="Class Probabilities")
                    
                    with gr.TabItem("👁️ Visual Explanation (Grad-CAM)"):
                        cam_output = gr.Image(label="Attention Heatmap", interactive=False)
                        gr.Markdown("*Warmer colors (Red/Yellow) indicate regions the AI focused on.*")

        
        # Functionality
        run_btn.click(
            fn=predict_advanced,
            inputs=[input_image, task_selector],
            outputs=[conf_labels, cam_output, result_html, diagnosis_state, confidence_state]
        )
        
        report_btn.click(
            fn=generate_pdf_wrapper,
            inputs=[input_image, cam_output, diagnosis_state, confidence_state],
            outputs=[report_file]
        )
        
        clear_btn.click(
            lambda: (None, None, None, None, None, None, None),
            outputs=[input_image, conf_labels, cam_output, result_html, report_file, diagnosis_state, confidence_state]
        )

    return app

if __name__ == "__main__":
    app = create_app_v2()
    print("Launching SSCLNet Pro on Port 7861...")
    # Theme passed here for Gradio 6.0+
    theme = gr.themes.Soft(
        primary_hue="teal",
        secondary_hue="slate",
        neutral_hue="slate",
    ).set(
        body_background_fill="*neutral_50",
        block_background_fill="white",
        button_primary_background_fill="*primary_600",
        button_primary_text_color="white",
    )
    app.launch()
